[package]

name = "iron_llvm"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"

[dependencies]
libc = "0.2"
llvm-sys = { git="https://github.com/SnirkImmington/llvm-sys.rs-fork-mirror" }

[build-dependencies]
cmake = "0.1.12"
